### ISSUE TITLE
CentOS / RHEL

### ISSUE THREAD

**Issue by dvinograd** [chef-cookbooks/drbd#5]
Hey guys,

This is going to be a short rant..

I don't know how can you claim this cookbook was tested on CentOS when it obviously wasn't. The following hard-coded package name is specific to Ubuntu/Debian:

```
package "drbd8-utils" do
```

Besides that, the following claim is nice but the cookbook doesn't actually do any of that:

> In CentOS it will subscribe to EL Repository to access necessary drbd rpm packages.

So, it seems like documentation was written, but not the code.

**Comment by haidangwa** [comment]
Should you leverage the yum-elrepo cookbook to configure/install the yum repo instead? There are cases where having the configuration hard-coded in this cookbook may not be do-able (i.e., behind the firewall installations). Also, drbd83 vs drbd84 offering, or make that an attribute that can be customized?

**Comment by haidangwa** [comment]
+1 for f2961a9

**Comment by tas50** [comment]
I think we can close this out at this point since we're installing RHEL/Fedora packages. Feel free to open up another issue if you think we're missing something.
